language: python
python:
  - "2.7"
before_install:
  - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
  - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
install:
  - sudo apt-get install git libgtk2.0-dev libglib2.0-dev
# install PyGObject from source
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
  - tar xf pygobject-2.28.6.tar.bz2
  - cd pygobject-2.28.6
  - ./configure --prefix=$VIRT_ROOT --disable-introspection > /dev/null
  - make > /dev/null
  - make install > /dev/null
  - cd ..
# install PyGTK from source
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xf pygtk-2.24.0.tar.bz2
  - cd pygtk-2.24.0
  - ./configure --prefix=$VIRT_ROOT
  - make > /dev/null
  - sudo make install
  - cd ..
# coveralls.io
  - pip install python-coveralls requests[security]
# install mock
  - pip install mock
script: make tests COVERAGE="coverage run --include='bleachbit/*'"
after_success:
   - mv .coverage .coverage.travis
   - sudo pip install appveyor-artifacts
   - appveyor-artifacts -o az0 -n bleachbit -m download
   - coverage combine
   - coverage report
   - coveralls
