name: Update translation in org.bleachbit.BleachBit.desktop

on:
  push:
    branches:
      - master
    paths:
      - 'po/*.po' # translation changed

jobs:
  update-desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget gettext
          wget https://raw.githubusercontent.com/bleachbit/bleachbit-misc/refs/heads/master/extract_desktop.py
          python3 -m pip install --upgrade pip setuptools

      - name: Run make command
        run: make -C po local

      - name: Run extract_desktop.py
        run: python3 extract_desktop.py

      # Generate NsisInclude/BleachBitLang.nsh from po/*.po
      - name: Run NSIS translation generator
        run: python3 windows/nsis_translations.py --generate

      - name: Commit if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add org.bleachbit.BleachBit.desktop windows/NsisInclude/NsisMultiUserLang.nsh
          if [ -z "$(git diff --cached --exit-code)" ]; then
              echo "No changes to commit."
          else
              git commit -m 'Update translation in .desktop file' -m 'Automatically extracted from ./po/*.po'
              git push
          fi

